// GENERATED from lead-manager/schema.sql by scripts/sync_schema.py: do not edit by hand.
export const SCHEMA = [
  "CREATE TABLE IF NOT EXISTS leads (\n  place_id            TEXT PRIMARY KEY,\n  name                TEXT NOT NULL,\n  trade               TEXT NOT NULL,\n  search_town         TEXT NOT NULL,\n  rank                INTEGER,\n  address             TEXT,\n  town                TEXT,\n  postcode            TEXT,\n  phone               TEXT,\n  website             TEXT,\n  maps_url            TEXT,\n  rating              REAL,\n  review_count        INTEGER,\n  email               TEXT,\n  emails              TEXT,   \n  socials             TEXT,   \n  issues              TEXT,   \n  audit               TEXT,   \n  director_first_name TEXT,\n  director_name       TEXT,\n  company_number      TEXT,\n  excluded            INTEGER NOT NULL DEFAULT 0,\n  exclude_reason      TEXT,\n  quality_score       INTEGER NOT NULL DEFAULT 0,\n  warmth_score        INTEGER NOT NULL DEFAULT 0,  \n  status              TEXT NOT NULL DEFAULT 'new', \n  notes               TEXT NOT NULL DEFAULT '',\n  last_job_id         TEXT,  \n  first_seen_at       TEXT NOT NULL,\n  updated_at          TEXT NOT NULL\n)",
  "CREATE INDEX IF NOT EXISTS leads_trade_town ON leads (trade, search_town)",
  "CREATE INDEX IF NOT EXISTS leads_quality ON leads (excluded, quality_score DESC)",
  "CREATE INDEX IF NOT EXISTS leads_job ON leads (last_job_id)",
  "CREATE TABLE IF NOT EXISTS jobs (\n  id          TEXT PRIMARY KEY,\n  trade       TEXT NOT NULL,\n  town        TEXT NOT NULL,\n  max_results INTEGER NOT NULL,\n  status      TEXT NOT NULL DEFAULT 'queued', \n  found       INTEGER,\n  pitchable   INTEGER,\n  error       TEXT,\n  created_at  TEXT NOT NULL,\n  updated_at  TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS scans (\n  id          TEXT PRIMARY KEY,\n  keyword     TEXT NOT NULL,\n  town        TEXT NOT NULL,\n  grid        INTEGER NOT NULL,             \n  spacing_m   INTEGER NOT NULL,             \n  center_lat  REAL,\n  center_lng  REAL,\n  source      TEXT NOT NULL DEFAULT 'manual', \n  status      TEXT NOT NULL DEFAULT 'queued', \n  error       TEXT,\n  created_at  TEXT NOT NULL,\n  updated_at  TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS scan_points (\n  scan_id  TEXT NOT NULL,\n  idx      INTEGER NOT NULL,\n  row      INTEGER NOT NULL,\n  col      INTEGER NOT NULL,\n  lat      REAL NOT NULL,\n  lng      REAL NOT NULL,\n  ranking  TEXT NOT NULL,  \n  PRIMARY KEY (scan_id, idx)\n)",
  "CREATE TABLE IF NOT EXISTS scan_businesses (\n  scan_id      TEXT NOT NULL,\n  place_id     TEXT NOT NULL,\n  name         TEXT,\n  rating       REAL,\n  review_count INTEGER,\n  avg_rank     REAL NOT NULL,   \n  top3_pct     INTEGER NOT NULL,\n  found_pct    INTEGER NOT NULL,\n  ranks        TEXT NOT NULL,   \n  PRIMARY KEY (scan_id, place_id)\n)",
  "CREATE TABLE IF NOT EXISTS lead_map_rank (\n  place_id   TEXT PRIMARY KEY,\n  scan_id    TEXT NOT NULL,\n  keyword    TEXT NOT NULL,\n  town       TEXT NOT NULL,\n  avg_rank   REAL NOT NULL,\n  top3_pct   INTEGER NOT NULL,\n  found_pct  INTEGER NOT NULL,\n  updated_at TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS job_progress (\n  job_id     TEXT PRIMARY KEY,\n  stage      TEXT NOT NULL,\n  done       INTEGER NOT NULL,\n  total      INTEGER NOT NULL,\n  scouted    INTEGER NOT NULL DEFAULT 0,  \n  updated_at TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS api_usage (\n  id         INTEGER PRIMARY KEY AUTOINCREMENT,\n  run_kind   TEXT NOT NULL,  \n  run_id     TEXT,\n  sku        TEXT NOT NULL,  \n  calls      INTEGER NOT NULL,\n  created_at TEXT NOT NULL\n)",
  "CREATE INDEX IF NOT EXISTS api_usage_date ON api_usage (created_at)",
  "CREATE TABLE IF NOT EXISTS clients (\n  id              TEXT PRIMARY KEY,\n  name            TEXT NOT NULL,\n  place_id        TEXT,            \n  package         TEXT NOT NULL,   \n  build_fee_pence INTEGER NOT NULL,\n  monthly_pence   INTEGER NOT NULL,\n  free_days       INTEGER NOT NULL,\n  paid_on         TEXT NOT NULL,   \n  cancelled_on    TEXT,            \n  notes           TEXT NOT NULL DEFAULT '',\n  created_at      TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS money (\n  id           TEXT PRIMARY KEY,\n  kind         TEXT NOT NULL,   \n  category     TEXT NOT NULL,\n  label        TEXT NOT NULL,\n  amount_pence INTEGER NOT NULL,\n  on_date      TEXT NOT NULL,   \n  monthly      INTEGER NOT NULL DEFAULT 0,\n  ended_on     TEXT,            \n  created_at   TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS settings (\n  key   TEXT PRIMARY KEY,\n  value TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS payments (\n  id              TEXT PRIMARY KEY,  \n  stripe_customer TEXT,\n  name            TEXT NOT NULL,\n  category        TEXT NOT NULL,     \n  amount_pence    INTEGER NOT NULL,\n  fee_pence       INTEGER NOT NULL DEFAULT 0,\n  paid_on         TEXT NOT NULL,     \n  created_at      TEXT NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS client_links (\n  client_id           TEXT PRIMARY KEY,\n  stripe_customer     TEXT NOT NULL,\n  stripe_subscription TEXT,\n  email               TEXT,\n  failed_on           TEXT  \n)"
];
